// Copyright (c) 2021 nikitapnn1@gmail.com
// This file is a part of npsystem (Distributed Control System) and covered by LICENSING file in the topmost directory

#pragma once

#include <boost/serialization/export.hpp>

#define NP_BOOST_CLASS_EXPORT_GUID(Class) \
	BOOST_CLASS_EXPORT_GUID(Class, NPG_ ## Class) 

#define NPG_CInput										"\x01"
#define NPG_COutput										"\x02"
#define NPG_COr												"\x03"
#define NPG_CAnd											"\x04"
#define NPG_CNot											"\x05"
#define NPG_CPositiveEdge							"\x06"
#define NPG_CNegativeEdge							"\x07"
#define NPG_CAnyEdge									"\x08"
#define NPG_CRsTrigger								"\x09"
#define NPG_CDelay										"\x0A"
#define NPG_CBinaryEncoder						"\x0B"
#define NPG_CBinaryDecoder						"\x0C"
#define NPG_CAdd											"\x0D"
#define NPG_CSub											"\x0E"
#define NPG_CMul											"\x0F"
#define NPG_CDiv											"\x10"
#define NPG_CPID											"\x11"
#define NPG_CAlarmHigh								"\x12"
#define NPG_CAlarmLow									"\x13"
#define NPG_CTextElement							"\x14"
#define NPG_CStaticTextElement				"\x15"
#define NPG_CDxEdit										"\x16"
#define NPG_CBlockVariableProperty		"\x17"
#define NPG_CBlockVariantProperty			"\x18"
#define NPG_CFBDBlockComposition			"\x19"
#define NPG_CBlockCompositionWrapper	"\x1A"
#define NPG_CLine											"\x1B"
#define NPG_CInputSlot								"\x1C"
#define NPG_COutputSlot								"\x1D"
#define NPG_CValue										"\x1E"
#define NPG_CBlockInput								"\x1F"
#define NPG_CInternalRef							"\x20"
#define NPG_CValueRef									"\x21"
#define NPG_CAvrInternalPin						"\x22"
#define NPG_CModuleValue							"\x23"
#define NPG_CExternalReference				"\x24"
#define NPG_BlockPropBool							"\x25"
#define NPG_BlockPropU8								"\x26"
#define NPG_BlockPropI8								"\x27"
#define NPG_BlockPropU16							"\x28"
#define NPG_BlockPropI16							"\x29"
#define NPG_BlockPropU32							"\x2A"
#define NPG_BlockPropI32							"\x2B"
#define NPG_BlockPropFloat						"\x2C"
#define NPG_BlockPropDouble						"\x2D"
#define NPG_BlockPropCString					"\x2E"
#define NPG_CTime											"\x2F"
#define NPG_CFixedValue								"\x30"
#define NPG_CComparator								"\x31"
#define NPG_CSlotGroup								"\x32"
#define NPG_CBlockFunction						"\x33"
#define NPG_CBlockSchedule						"\x34"
#define NPG_CScheduleSlider						"\x35"
#define NPG_CSliderTimeChart					"\x36"
#define NPG_CSliderThing							"\x37"
#define NPG_CCounter									"\x38"
#define NPG_CPulse										"\x39"
#define NPG_CSFCBlockComposition			"\x3A"
#define NPG_CSFCBlockStep							"\x3B"
#define NPG_CSFCBlockTransition				"\x3C"
#define NPG_CSFCInputSlot							"\x3D"
#define NPG_CSFCOutputSlot						"\x3E"
#define NPG_CSFCLine									"\x3F"
#define NPG_CSFCBlockBegin						"\x40"
#define NPG_CSFCBlockTerm							"\x41"