//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by npsystem.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_DROP                        103
#define IDC_POINTER                     104
#define IDC_POINTER_COPY                105
#define IDC_NODROP                      106
#define IDR_MAINFRAME                   128
#define IDR_VIEW                        129
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDD_ALGORITHM_PROPERTIES        205
#define IDI_PINNED                      208
#define IDI_UNPINNED                    209
#define IDD_DLG_SET_INPUTS              209
#define IDD_DLG_SIMPLE_INPUT            209
#define IDD_DIALOG1                     213
#define IDD_DLG_LOADING_MANAGER         213
#define IDD_DIALOG2                     215
#define IDD_DLG_PARAMETER               215
#define IDD_DIALOG3                     217
#define IDD_DLG_BLOCK_FUNCTION          217
#define IDD_DLG_MODULE                  310
#define IDD_DLG_NEWFILE                 313
#define IDD_DLG_LIBPROPERTIES           314
#define IDD_DLG_SEGMENTVALUE            315
#define IDD_DLG_SEGMENT                 316
#define IDD_DLG_DOCLIST                 317
#define IDD_DLG_ONLINELIST              319
#define IDI_FILE_ICON                   326
#define IDI_FOLDER_CLOSE                329
#define IDI_FOLDER_OPEN                 330
#define IDI_MODULES                     333
#define IDI_MODULE                      334
#define IDI_TXT_FILE                    335
#define IDI_H_FILE                      336
#define IDI_C_FILE                      338
#define IDI_S_FILE                      339
#define IDI_FILE_DELETE                 340
#define IDI_EXCLAM                      343
#define IDI_EMPTY                       344
#define IDI_CTRL_DEV                    345
#define IDI_BOOK                        347
#define IDI_LIBRARY                     348
#define IDI_FUNCTIONS                   349
#define IDI_FUN                         351
#define IDI_SOURCE                      353
#define IDI_BINARY                      354
#define IDI_PC                          355
#define IDI_ICON1                       356
#define IDI_CHIP                        357
#define IDC_PEN                         359
#define IDI_ICON2                       362
#define IDC_CURSOR2                     368
#define IDC_LINKSEL                     368
#define IDI_VAR                         370
#define IDI_NP_QUESTION                 371
#define IDR_MENU_ALG_CONTEXT            376
#define IDR_MENU_ALG_CONTEXT_SELECTED   377
#define IDR_MENU_ALG_CONTEXT_BLOCK      378
#define IDD_DLG_CONTROLLER              403
#define IDD_DLG_NEW_CONTROLLER          405
#define IDD_DLG_IOBLOCK                 407
#define IDD_DLG_PROGRAMMER              408
#define IDD_DLG_ONLINE_DISCRETE         410
#define IDD_DLG_PINCONFIG               412
#define IDD_DLG_ONLINE                  413
#define IDD_DLG_ALGORITHM_PROPERTIES    414
#define IDD_DLG_SEGMENT2                415
#define IDI_CONTROLLERS                 441
#define IDI_CTRL_GOOD                   441
#define IDI_CTRL_BAD                    442
#define IDI_CTRL_NL                     443
#define IDI_ALGORITHM                   459
#define IDI_SYSTEM                      460
#define IDI_INPUTS                      468
#define IDI_OUTPUTS                     469
#define IDI_ALG_NL                      470
#define IDI_ALG_LA                      471
#define IDI_HARDWARE                    473
#define IDI_SOFTWARE                    474
#define IDI_OPIN                        479
#define IDI_MPIN                        480
#define IDI_EX                          481
#define IDI_AI_PIN                      499
#define IDI_DI_PIN                      500
#define IDI_DO_PIN                      501
#define IDI_STOP_BUTTON                 504
#define IDI_START_BUTTON                506
#define IDI_MAIN                        512
#define IDI_IO                          513
#define IDI_I2C                         514
#define IDI_CONTAINER                   515
#define IDI_NETWORK                     516
#define IDI_BLOCK                       517
#define IDD_DLG_AVR_MEMORY_VIEWER       606
#define IDD_DLG_CONFIGURABLE_BLOCK      607
#define IDD_DLG_STRING                  608
#define IDC_RADIO_BT_1                  1000
#define IDC_RADIO_BT_2                  1001
#define IDC_RADIO_BT_3                  1002
#define IDC_RADIO_BT_4                  1003
#define IDC_TREE1                       1003
#define IDC_RADIO_BT_5                  1004
#define IDC_PROGRESS1                   1004
#define IDC_RADIO_BT_6                  1005
#define IDC_CUSTOM1                     1005
#define IDC_RADIO_BT_7                  1006
#define IDC_RADIO_BT_8                  1007
#define IDC_RADIO_BT_9                  1008
#define IDC_RADIO_BT_10                 1009
#define IDC_RADIO_BT_11                 1010
#define IDC_RADIO_BT_12                 1011
#define IDC_RADIO_BT_13                 1012
#define IDC_RADIO_BT_14                 1013
#define IDC_RADIO_BT_15                 1014
#define IDC_RADIO_BT_16                 1015
#define IDC_RADIO_BT_17                 1016
#define IDC_RADIO_BT_18                 1017
#define IDC_RADIO_BT_19                 1018
#define IDC_RADIO_BT_20                 1019
#define IDC_RADIO_BT_FALSE              1020
#define IDC_RADIO_BT_TRUE               1021
#define IDC_COMBO1                      1122
#define IDC_COMBO2                      1123
#define IDC_COMBO3                      1124
#define IDC_COMBO4                      1125
#define IDC_COMBO5                      1126
#define IDC_EDIT1                       1227
#define IDC_EDIT2                       1228
#define IDC_EDIT3                       1229
#define IDC_EDIT4                       1230
#define IDC_EDIT5                       1231
#define IDC_EDIT_NAME                   1232
#define IDC_EDIT_LINK                   1233
#define IDC_CHECK1                      1332
#define IDC_CHECK2                      1333
#define IDC_CHECK3                      1334
#define IDC_CHECK4                      1335
#define IDC_CHECK5                      1336
#define IDC_CHECK6                      1337
#define IDC_CHECK7                      1338
#define IDC_CHECK8                      1339
#define IDC_CHECK9                      1340
#define IDC_CHECK10                     1341
#define IDC_BUTTON1                     1442
#define IDC_BUTTON2                     1443
#define IDC_BUTTON3                     1444
#define IDC_BUTTON4                     1445
#define IDC_BUTTON5                     1446
#define IDC_BUTTON6                     1447
#define IDC_BUTTON7                     1448
#define IDC_BUTTON8                     1449
#define IDC_BUTTON9                     1450
#define IDC_BUTTON10                    1451
#define IDC_LIST1                       1552
#define IDC_LIST2                       1553
#define IDC_LIST3                       1554
#define ID_POPUP_PROPERTIES             32775
#define ID_VIEW_TREEPANE                36774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        220
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
